// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFUFEpZuzC0EJdZLQ6PKM1pFlicRoTPaY',
    appId: '1:762325685309:web:729dab0bb17f56c71b8654',
    messagingSenderId: '762325685309',
    projectId: 'xerox-01-04',
    authDomain: 'xerox-01-04.firebaseapp.com',
    storageBucket: 'xerox-01-04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDglg2sk4k-VwJb6-szJx17aAfHG4HB5x0',
    appId: '1:762325685309:android:107afb251d4c901f1b8654',
    messagingSenderId: '762325685309',
    projectId: 'xerox-01-04',
    storageBucket: 'xerox-01-04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNLBvU7YpTrNaXl_cVBhh0dxjbkpMyu-U',
    appId: '1:762325685309:ios:84789c3e38035f031b8654',
    messagingSenderId: '762325685309',
    projectId: 'xerox-01-04',
    storageBucket: 'xerox-01-04.appspot.com',
    iosClientId: '762325685309-gsgo9snbmq85j75cr01m60glooml5sff.apps.googleusercontent.com',
    iosBundleId: 'com.example.xerox',
  );
}
